In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [2]:
import math

**Уровень 0**

**a**

In [63]:
T = np.array([[0, 1], [-1, 0]])

In [64]:
TT = T.transpose()
TT

array([[ 0, -1],
       [ 1,  0]])

In [65]:
T.dot(TT)

array([[1, 0],
       [0, 1]])

**b**

In [66]:
A = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])

In [67]:
A

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [68]:
AT = A.transpose()

In [69]:
AT

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [70]:
A.dot(AT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**c**

In [80]:
B = np.array([[0, 0, -1], [0, 1, 0], [-1, 0, 0]])

In [81]:
BT = B.transpose()

In [82]:
B.dot(BT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**d**

In [35]:
a = np.array([[2, 1],
              [3, 2]])

In [36]:
np.linalg.det(a)

0.9999999999999998

собственные значения и векторы

In [12]:
m = np.array([[2, 2],
              [1, 3]])

np.linalg.eig(m)

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))