**1**

In [7]:
import numpy as np

N = int(input())
my_array = np.arange(N, -1, -1)
print(my_array)

3
[3 2 1 0]


**2**

In [9]:
np.diag(my_array, k=0)


array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

**3**

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [10]:
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 4, 0] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([-5.18181818,  5.72727273, 13.27272727])

**4**

In [41]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
cos_sim_list = {}

for user in users_stats:
  scalar = np.dot(user, next_user_stats)
  cos_sim = scalar/ (np.linalg.norm(user) * np.linalg.norm(next_user_stats))
  cos_sim_list[tuple(user)] = round(cos_sim, 2)

# print(cos_sim_list)
# # print(round(max(cos_sim_list), 2))


max_value = max(cos_sim_list.values()) 
max_keys = [k for k, v in cos_sim_list.items() if v == max_value]

print(f'Самый похожий пользователь это {max_keys}, его косинусное сходство с новым пользователем приблизтельно равно {max_value}')



Самый похожий пользователь это [(0, 1, 1, 0, 0, 0)], его косинусное сходство с новым пользователем приблизтельно равно 0.95
